---
title: "ggplot2 figures for article"
author: "Meng Le Zhang"
date: "12 March 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(tidyverse)
library(gridExtra)
```

# This is a guide for producting the figures used in the RCI 1 paper article.

##  Plot one: The Relative centralisation index
The first plot is the one we need to explain visually what the Gini and Duncan indicies do. 

```{r plot of duncan}

gg.tab <- 'C:/Users/Meng Le Zheng/Google Drive/UK RCI paper 1/R project code/Graphs and tables/rci curve tab.csv' %>% read.csv
green <- rgb(0.4, 1, 0.4, alpha=0.25)

print(gg.tab)

duncan <- ggplot(gg.tab, aes(x = prop.nonpoor, y = prop.poor)) + geom_line() + 
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed') +
  geom_ribbon(aes(ymin = prop.nonpoor, ymax = prop.poor, fill = green, alpha = 0.5)) +
  scale_fill_manual(values=c(green)) + 
  theme(legend.position="none", plot.title = element_text(hjust = 0.5)) + 
  ggtitle('Relative centralisation index') +
  theme(text = element_text(size = 12)) + 
  ylab('Cumulative prop. of poor ranked by distance to centre (low to high)') +
  xlab('Cumulative prop. of non-poor ranked by distance to centre (low to high)')

print(duncan)


```

## Plot 2: Scatterplot showing RCI in various years

This will be the RCI type plots

```{r rci plots}
rci.res <- 'C:/Users/Meng Le Zheng/Google Drive/UK RCI paper 1/Results/RCI TTWA CI.csv' %>% read.csv
point.tab <- 'C:/Users/Meng Le Zheng/Google Drive/UK RCI paper 1/Results/RCI  BUA jsa point estimates.csv' %>%
  read.csv
rci.res <- point.tab %>% merge(rci.res, by = 'ttwa')
point.tab$ttwa %>% subset(!(point.tab$ttwa %in% rci.res$ttwa)) #no penzance
names(rci.res)

rci1 <- ggplot(data = rci.res, aes(x = rci01.50., y = rci11.50.)) + geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed') +
  geom_hline(yintercept = 0) + geom_vline(xintercept = 0) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('2011') + xlab('2001') +
  ggtitle('RCI in 2001 and 2011')


rci2 <- ggplot(data = rci.res, aes(x = log(pop), y = rcidiff.50.)) + 
  geom_point() + geom_smooth(alpha = 0.2) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Change in RCI') + xlab('Population (log)')+
  ggtitle('RCI change by population (loess curve)') +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed')

rci.toptemp <- rci.res[order(-1 * rci.res$pop)[1:10], ]
rci.topten <- data.frame(ttwa = factor(rci.toptemp$ttwa, 
                                       levels = rci.toptemp$ttwa),
                         rci = c(rci.toptemp$rci01.50., rci.toptemp$rci11.50.),
                         lo.rci = c(rci.toptemp$rci01.2.5., rci.toptemp$rci11.2.5.),
                         hi.rci = c(rci.toptemp$rci01.97.5., rci.toptemp$rci11.97.5.),
                         year = c(rep('2001', 10), rep('2011', 10)))

rci3 <- ggplot(data = rci.topten, aes(x = ttwa, y = rci, fill = year)) + 
  geom_bar(stat='identity', position=position_dodge()) +
  geom_errorbar(data = rci.topten, 
                aes(x = ttwa, ymin = lo.rci, ymax = hi.rci),
                alpha = 0.5,
                position=position_dodge()) +
  theme(axis.text.x = element_text(angle = 15, hjust = 1, size = 8),
        plot.title = element_text(hjust = 0.5),
        legend.position = c(0.1, 0.9),
        legend.background = element_rect(fill="transparent"),
        legend.title = element_blank(),
        legend.direction = 'horizontal') +
  ylab('RCI') + 
  xlab('')+
  ggtitle('RCI for most populated TTWAs with 95% credible intervals') 

grid.arrange(rci3, rci1, rci2, 
             layout_matrix = rbind(c(1, 1),
                                   c(2, 3))
)



```

##  Plot 3: Change in relative access index

```{r relative access}
rae.res <- 'C:/Users/Meng Le Zheng/Google Drive/UK RCI paper 1/Results/RCI emp jsa point estimates weighted rci.csv' %>% read.csv
ci.res <- 'C:/Users/Meng Le Zheng/Google Drive/UK RCI paper 1/Results/RAE TTWA total CI.csv' %>% read.csv
rae.res <- rae.res %>% merge(ci.res, by = 'ttwa')
names(rae.res)

rae1 <- ggplot(data = rae.res, aes(x = ttwa.tot.rci01, y = ttwa.tot.rci11)) + geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed') +
  geom_hline(yintercept = 0) + geom_vline(xintercept = 0) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('2011') + xlab('2001') +
  ggtitle('RAE in 2001 and 2011')

rae2 <- ggplot(data = rae.res, aes(x = log(pop), y = ttwa.tot.rci.diff)) + 
  geom_point() + geom_smooth(alpha = 0.2) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Change in RAE') + xlab('Population (log)')+
  ggtitle('Change by population (loess curve)') +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed')

rae.toptemp <- rae.res[order(-1 * rae.res$pop)[1:10], ]
rae.topten <- data.frame(ttwa = factor(rae.toptemp$ttwa, 
                                       levels = rae.toptemp$ttwa), 
                         rci = c(rae.toptemp$rci01.50., rae.toptemp$rci11.50.),
                         lo.rci = c(rae.toptemp$rci01.2.5., rae.toptemp$rci11.2.5.),
                         hi.rci = c(rae.toptemp$rci01.97.5., rae.toptemp$rci11.97.5.),
                         year = c(rep('2001', 10), rep('2011', 10)))

rae3 <- ggplot(data = rae.topten, aes(x = ttwa, y = rci, fill = year)) + 
  geom_bar(stat='identity', position=position_dodge()) +
  geom_errorbar(data = rae.topten, 
                aes(x = ttwa, ymin = lo.rci, ymax = hi.rci),
                alpha = 0.5,
                position=position_dodge()) +
    theme(axis.text.x = element_text(angle = 15, hjust = 1, size = 10),
        plot.title = element_text(hjust = 0.5),
        legend.position = c(0.5, 0.9),
        legend.background = element_rect(fill="transparent"),
        legend.title = element_blank(),
        legend.direction = 'horizontal') +
  ylab('RAE') + 
  xlab('')+
  ggtitle('RAE for most populated TTWAs with 95% credible intervals') 


grid.arrange(rae3, rae1, rae2, 
             layout_matrix = rbind(c(1, 1),
                                   c(2, 3))
)


```


##  Plot 4: Geographical barriers to access
```{r geo barriers}

geo.res <- 'C:/Users/Meng Le Zheng/Google Drive/UK RCI paper 1/Results/Geographical barriers index point est.csv' %>% read.csv
geo.res <- geo.res %>% subset(!(ttwa %in% c('Newport & Cwmbran')))
rci.res <- 'C:/Users/Meng Le Zheng/Google Drive/UK RCI paper 1/Results/RCI  BUA jsa point estimates.csv' %>% read.csv
geo.res <- geo.res %>% merge(rci.res[, c('ttwa', 'pop')])

ci.res <- 'C:/Users/Meng Le Zheng/Google Drive/UK RCI paper 1/Results/GEO TTWA CI.csv' %>% read.csv
geo.res <- geo.res %>% merge(ci.res, by = 'ttwa')


rci1 <- ggplot(data = geo.res, aes(x = geo01.rci, y = geo11.rci)) + geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed') +
  geom_hline(yintercept = 0) + geom_vline(xintercept = 0) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('2011') + xlab('2001') +
  ggtitle('Proximity to amenities index in 2001 and 2011')

rci2 <- ggplot(data = geo.res, aes(x = log(pop), y = geo.diff)) + 
  geom_point() + geom_smooth(alpha = 0.2) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab('Change in index') + xlab('Population (log)')+
  ggtitle('Change by population (loess curve, England)') +
  geom_abline(slope = 1, intercept = 0, linetype = 'dashed')

rci.toptemp <- geo.res[order(-1 * geo.res$pop)[1:10], ]

rci.topten <- data.frame(ttwa = factor(rci.toptemp$ttwa, 
                                       levels = rci.toptemp$ttwa), 
                         rci = c(rci.toptemp$rci01.50., rci.toptemp$rci11.50.),
                         lo.rci = c(rci.toptemp$rci01.2.5., rci.toptemp$rci11.2.5.),
                         hi.rci = c(rci.toptemp$rci01.97.5., rci.toptemp$rci11.97.5.),
                         year = c(rep('2001', 10), rep('2011', 10)))

rci3 <- ggplot(data = rci.topten, aes(x = ttwa, y = rci, fill = year)) + 
  geom_bar(stat='identity', position=position_dodge()) +
  geom_errorbar(data = rci.topten, 
                aes(x = ttwa, ymin = lo.rci, ymax = hi.rci),
                alpha = 0.5,
                position=position_dodge()) +
  theme(axis.text.x = element_text(angle = 15, hjust = 1, size = 10),
        plot.title = element_text(hjust = 0.5),
        legend.position = c(0.1, 0.9),
        legend.background = element_rect(fill="transparent"),
        legend.title = element_blank(),
        legend.direction = 'horizontal') +
  ylab('Amenities index') + 
  xlab('')+
  ggtitle('Proximity to amenities index for most populated TTWAs (England) with 95% credible intervals') 

grid.arrange(rci3, rci1, rci2, 
             layout_matrix = rbind(c(1, 1),
                                   c(2, 3))
)

```